package gdg.sharinglog.rotation.engine;

public enum SelectionReasonCode {
    ACTIVE_ELIGIBLE_NOT_DECLINED_FILTER,
    MINIMUM_SAME_CHORE_COMPLETION_COUNT,
    MINIMUM_ACTIVE_PERIOD_LOAD,
    PREVIOUS_ASSIGNEE_DEPRIORITIZED,
    PREVIOUS_ASSIGNEE_WAS_ONLY_REMAINING_OPTION,
    SOLE_FINALIST,
    RANDOM_TIE_BREAK,
    NO_ASSIGNABLE_CANDIDATE
}
